
/*************************************************************************
 > File Name: Menu.h
 > Description:
 > 	Generated by script
 ************************************************************************/
#ifndef __MENU_H__
#define __MENU_H__
#include <minigui/common.h>
#include <minigui/minigui.h>
#include <minigui/gdi.h>
#include <minigui/window.h>
#include <minigui/control.h>

#include "windows.h"
#include "cdr_widgets.h"
#include "keyEvent.h"
#include "cdr_message.h"
#include "StorageManager.h"
#include "resourceManager.h"

#ifdef MODEM_ENABLE
#define MENU_LIST_COUNT  20
#else
#define MENU_LIST_COUNT  19
#endif
enum menuIndex {
	MENU_INDEX_VQ,
	MENU_INDEX_PQ,
	MENU_INDEX_VTL,
	MENU_INDEX_AWMD,
	MENU_INDEX_WB,
	MENU_INDEX_CONTRAST,
	MENU_INDEX_EXPOSURE,
	MENU_INDEX_POR,
	MENU_INDEX_GPS,
#ifdef MODEM_ENABLE
	MENU_INDEX_CELLULAR,
#endif
	MENU_INDEX_SS,
	MENU_INDEX_SILENTMODE,
	MENU_INDEX_WIFI,
	MENU_INDEX_AP,
	MENU_INDEX_DATE,
	MENU_INDEX_LANG,
	MENU_INDEX_TWM,
	MENU_INDEX_FORMAT,
	MENU_INDEX_FRESET,
	MENU_INDEX_FIRMWARE
};

enum ResourceID menuResourceID[] = {
	ID_MENU_LIST_VQ,
	ID_MENU_LIST_PQ,
	ID_MENU_LIST_VTL,
	ID_MENU_LIST_AWMD,
	ID_MENU_LIST_WB,
	ID_MENU_LIST_CONTRAST,
	ID_MENU_LIST_EXPOSURE,
	ID_MENU_LIST_POR,
	ID_MENU_LIST_GPS,
#ifdef MODEM_ENABLE
	ID_MENU_LIST_CELLULAR,
#endif
	ID_MENU_LIST_SS,
	ID_MENU_LIST_SILENTMODE,
	ID_MENU_LIST_WIFI,
	ID_MENU_LIST_AP,
	ID_MENU_LIST_DATE,
	ID_MENU_LIST_LANG,
	ID_MENU_LIST_TWM,
	ID_MENU_LIST_FORMAT,
	ID_MENU_LIST_FRESET,
	ID_MENU_LIST_FIRMWARE
};

unsigned int haveCheckBox[] = {
	0, 	/*VQ 		 not have check box */
	0, 	/*PQ 		 not have check box */
	0, 	/*VTL 		 not have check box */
	1, 	/*AWMD 		 have check box */
	0, 	/*WB 		 not have check box */
	0, 	/*CONTRAST 		 not have check box */
	0, 	/*EXPOSURE 		 not have check box */
	1, 	/*POR 		 have check box */
	1, 	/*GPS 		 have check box */
#ifdef MODEM_ENABLE
	1,      /*CELLULAR       have check box */
#endif
	0, 	/*SS 		 not have check box */
	1, 	/*SILENTMODE 		 have check box */
	1, 	/*WIFI 		 have check box */
	0, 	/*AP		 not have check box */
	0, 	/*DATE 		 not have check box */
	0, 	/*LANG 		 not have check box */
	1, 	/*TWM 		 have check box */
	0, 	/*FORMAT 		 not have check box */
	0, 	/*FRESET 		 not have check box */
	0 	/*FIRMWARE 		 not have check box */
};

unsigned int haveSubMenu[] = {
	1, 	/*VQ 		 have sub menu */
	1, 	/*PQ 		 have sub menu */
	1, 	/*VTL 		 have sub menu */
	0, 	/*AWMD 		 not have sub menu */
	1, 	/*WB 		 have sub menu */
	1, 	/*CONTRAST 		 have sub menu */
	1, 	/*EXPOSURE 		 have sub menu */
	0, 	/*POR 		 not have sub menu */
	0, 	/*GPS 		 not have sub menu */
#ifdef MODEM_ENABLE
	0,      /*CELLULAR       not have sub menu */
#endif
	1, 	/*SS 		 have sub menu */
	0, 	/*SILENTMODE 		 not have sub menu */
	0, 	/*WIFI 		 not have sub menu */
	0, 	/*AP 		 not have sub menu */
	0, 	/*DATE 		 not have sub menu */
	1, 	/*LANG 		 have sub menu */
	0, 	/*TWM 		 not have sub menu */
	0, 	/*FORMAT 		 not have sub menu */
	0, 	/*FRESET 		 not have sub menu */
	0 	/*FIRMWARE 		 not have sub menu */
};

unsigned int haveValueString[] = {
	1, 	/*VQ 		 have value string */
	1, 	/*PQ 		 have value string */
	1, 	/*VTL 		 have value string */
	0, 	/*AWMD 		 not have value string */
	1, 	/*WB 		 have value string */
	1, 	/*CONTRAST 		 have value string */
	1, 	/*EXPOSURE 		 have value string */
	0, 	/*POR 		 not have value string */
	0, 	/*GPS 		 not have value string */
#ifdef MODEM_ENABLE
	0,      /*CELLULAR       not have value string */
#endif
	1, 	/*SS 		 have value string */
	0, 	/*SILENTMODE 		 not have value string */
	0, 	/*WIFI 		 not have value string */
	1, 	/*AP 		 have value string */
	0, 	/*DATE 		 not have value string */
	1, 	/*LANG 		 have value string */
	0, 	/*TWM 		 not have value string */
	0, 	/*FORMAT 		 not have value string */
	0, 	/*FRESET 		 not have value string */
	1 	/*FIRMWARE 		 not have value string */
};


int subMenuContent0Cmd[] = {
	LANG_LABEL_SUBMENU_VQ_CONTENT0,
	LANG_LABEL_SUBMENU_PQ_CONTENT0,
	LANG_LABEL_SUBMENU_VTL_CONTENT0,
	-1, 	/*AWMD not have sub menu */
	LANG_LABEL_SUBMENU_WB_CONTENT0,
	LANG_LABEL_SUBMENU_CONTRAST_CONTENT0,
	LANG_LABEL_SUBMENU_EXPOSURE_CONTENT0,
	-1, 	/*POR not have sub menu */
	-1, 	/*GPS not have sub menu */
#ifdef MODEM_ENABLE
	-1,     /*CELLULAR not have sub menu */
#endif
	LANG_LABEL_SUBMENU_SS_CONTENT0,
	-1, 	/*SILENTMODE not have sub menu */
	-1, 	/*WIFI not have sub menu */
	-1, 	/*AP not have sub menu */
	-1, 	/*DATE not have sub menu */
	LANG_LABEL_SUBMENU_LANG_CONTENT0,
	-1, 	/*TWM not have sub menu */
	-1, 	/*FORMAT not have sub menu */
	-1, 	/*FRESET not have sub menu */
	-1 	/*FIRMWARE not have sub menu */
};


MLFlags mlFlags[MENU_LIST_COUNT] = {
/***** 1. image flag	2. value flags	3. value counts *****************/
	/*VQ*/
	{ IMGFLAG_IMAGE, {VMFLAG_STRING, VMFLAG_IMAGE}, 2},

	/*PQ*/
	{ IMGFLAG_IMAGE, {VMFLAG_STRING, VMFLAG_IMAGE}, 2},

	/*VTL*/
	{ IMGFLAG_IMAGE, {VMFLAG_STRING, VMFLAG_IMAGE}, 2},

	/*AWMD*/
	{ IMGFLAG_IMAGE, {VMFLAG_IMAGE}, 1},

	/*WB*/
	{ IMGFLAG_IMAGE, {VMFLAG_STRING, VMFLAG_IMAGE}, 2},

	/*CONTRAST*/
	{ IMGFLAG_IMAGE, {VMFLAG_STRING, VMFLAG_IMAGE}, 2},

	/*EXPOSURE*/
	{ IMGFLAG_IMAGE, {VMFLAG_STRING, VMFLAG_IMAGE}, 2},

	/*POR*/
	{ IMGFLAG_IMAGE, {VMFLAG_IMAGE}, 1},

	/*GPS*/
	{ IMGFLAG_IMAGE, {VMFLAG_IMAGE}, 1},

#ifdef MODEM_ENABLE
        /*CELLULAR*/
        { IMGFLAG_IMAGE, {VMFLAG_IMAGE}, 1},
#endif

	/*SS*/
	{ IMGFLAG_IMAGE, {VMFLAG_STRING, VMFLAG_IMAGE}, 2},

	/*SILENTMODE*/
	{ IMGFLAG_IMAGE, {VMFLAG_IMAGE}, 1},

	/*WIFI*/
	{ IMGFLAG_IMAGE, {VMFLAG_IMAGE}, 1},

	/*AP*/
	{ IMGFLAG_IMAGE, {0}, 0},

	/*DATE*/
	{ IMGFLAG_IMAGE, {0}, 0},

	/*LANG*/
	{ IMGFLAG_IMAGE, {VMFLAG_STRING, VMFLAG_IMAGE}, 2},

	/*TWM*/
	{ IMGFLAG_IMAGE, {VMFLAG_IMAGE}, 1},

	/*FORMAT*/
	{ IMGFLAG_IMAGE, {0}, 0},

	/*FRESET*/
	{ IMGFLAG_IMAGE, {0}, 0},

	/*FIRMWARE*/
	{ IMGFLAG_IMAGE, {VMFLAG_STRING}, 1},
};


#endif

