
/*************************************************************************
 > File Name: NewMenu.h
 > Description:
 > 	Generated by script
 ************************************************************************/
#ifndef __NEWMENU_H__
#define __NEWMENU_H__
#include <minigui/common.h>
#include <minigui/minigui.h>
#include <minigui/gdi.h>
#include <minigui/window.h>
#include <minigui/control.h>

#include "windows.h"
#include "cdr_widgets.h"
#include "keyEvent.h"
#include "cdr_message.h"
#include "StorageManager.h"
#include "resourceManager.h"

#ifdef MODEM_ENABLE
#define MENU_LIST_MAX_COUNT 20
#else
#define MENU_LIST_MAX_COUNT 19
#endif

#define RP_ICON_COUNT 4
#define RP_SETTING_MENU_COUNT 16
enum ResourceID rpMenuResourceID[] = {
	ID_MENU_LIST_VQ,
	ID_MENU_LIST_VTL,
	ID_MENU_LIST_VM,
	ID_MENU_LIST_VIDEO_SETTING,
	ID_MENU_LIST_AWMD,
	ID_MENU_LIST_WB,
	ID_MENU_LIST_CONTRAST,
	ID_MENU_LIST_EXPOSURE,
	ID_MENU_LIST_POR,
	ID_MENU_LIST_GPS,
#ifdef MODEM_ENABLE
	ID_MENU_LIST_CELLULAR,
#endif
	ID_MENU_LIST_SS,
	ID_MENU_LIST_SILENTMODE,
	ID_MENU_LIST_WIFI,
	ID_MENU_LIST_AP,
	ID_MENU_LIST_DATE,
	ID_MENU_LIST_LANG,
	ID_MENU_LIST_TWM,
	ID_MENU_LIST_FORMAT,
	ID_MENU_LIST_FRESET,
	ID_MENU_LIST_FIRMWARE
};

#define PP_ICON_COUNT 2
#define PP_SETTING_MENU_COUNT 15
enum ResourceID ppMenuResourceID[] = {
	ID_MENU_LIST_PQ,
	ID_MENU_LIST_PHOTO_SETTING,
	ID_MENU_LIST_WB,
	ID_MENU_LIST_CONTRAST,
	ID_MENU_LIST_EXPOSURE,
	ID_MENU_LIST_POR,
	ID_MENU_LIST_GPS,
#ifdef MODEM_ENABLE
	ID_MENU_LIST_CELLULAR,
#endif
	ID_MENU_LIST_SS,
	ID_MENU_LIST_SILENTMODE,
	ID_MENU_LIST_WIFI,
	ID_MENU_LIST_AP,
	ID_MENU_LIST_DATE,
	ID_MENU_LIST_LANG,
	ID_MENU_LIST_TWM,
	ID_MENU_LIST_FORMAT,
	ID_MENU_LIST_FRESET,
	ID_MENU_LIST_FIRMWARE
};

enum mbIconIndex{
	MB_ICON_WIN0 = 0,
	MB_ICON_WIN1,
	MB_ICON_WIN2,
	MB_ICON_WIN3,
};

#define MENUBAR_MAX_COUNT 4
#endif

