#ifndef _CONFIG_H
#define _CONFIG_H

#define DEFAULT_NAME		"CarS---AP"
#define DEFAULT_PASSWORD	"12345678"
#define SOFTAP_GATEWAY_ADDR	"192.168.43.1"
#define SOFTAP_CLIENT_NUM	10

#define SOFTAP_UPSTREAM_INTERFACE	"veth0"
#define VETH_NETID			200
#define WIFI_NETID			100

#endif
