  
#ifndef __CDRLANG_H__
#define __CDRLANG_H__

#include <utils/Vector.h>
#include <utils/String8.h>

#include <minigui/common.h>
#include <minigui/gdi.h>

#include "cdr.h"







enum LANG_STRINGS {
	LANG_LABEL_MENU = 0,
	LANG_LABEL_MENU_VQ,
	LANG_LABEL_MENU_PQ,
	LANG_LABEL_MENU_VTL,
	LANG_LABEL_MENU_IDD,
	LANG_LABEL_MENU_IDR,
	LANG_LABEL_MENU_WB,
	LANG_LABEL_MENU_CONTRAST,
	LANG_LABEL_MENU_EXPOSURE,
	LANG_LABEL_MENU_POR,
	LANG_LABEL_MENU_GPS,
	LANG_LABEL_MENU_CELLULAR,
	LANG_LABEL_MENU_SS,
	LANG_LABEL_MENU_SILENTMODE,
	LANG_LABEL_MENU_WIFI,
	LANG_LABEL_MENU_AP,
	LANG_LABEL_MENU_DATE,
	LANG_LABEL_MENU_LANG,
	LANG_LABEL_MENU_TWM,
	LANG_LABEL_MENU_FORMAT,
	LANG_LABEL_MENU_FRESET,
	LANG_LABEL_MENU_AWMD,
	LANG_LABEL_MENU_FIRMWARE,
	LANG_LABEL_MENU_TMX,
	LANG_LABEL_SUBMENU_LANG_TITLE,
	LANG_LABEL_SUBMENU_LANG_CONTENT0,
	LANG_LABEL_SUBMENU_LANG_CONTENT1,
	LANG_LABEL_SUBMENU_LANG_CONTENT2,
	LANG_LABEL_SUBMENU_LANG_CONTENT3,
	LANG_LABEL_SUBMENU_LANG_CONTENT4,
	LANG_LABEL_SUBMENU_LANG_CONTENT5,
	LANG_LABEL_SUBMENU_VQ_TITLE,
	LANG_LABEL_SUBMENU_VQ_CONTENT0,
	LANG_LABEL_SUBMENU_VQ_CONTENT1,
#ifdef USE_NEWUI
	LANG_LABEL_SUBMENU_VM_TITLE,
	LANG_LABEL_SUBMENU_VM_CONTENT0,
	LANG_LABEL_SUBMENU_VM_CONTENT1,
	LANG_LABEL_SUBMENU_VM_CONTENT2,
#endif
	LANG_LABEL_SUBMENU_PQ_TITLE,
	LANG_LABEL_SUBMENU_PQ_CONTENT0,
	LANG_LABEL_SUBMENU_PQ_CONTENT1,
	LANG_LABEL_SUBMENU_PQ_CONTENT2,
	LANG_LABEL_SUBMENU_PQ_CONTENT3,
	LANG_LABEL_SUBMENU_VTL_TITLE,
	LANG_LABEL_SUBMENU_VTL_CONTENT0,
	LANG_LABEL_SUBMENU_VTL_CONTENT1,
#ifdef USE_NEWUI
	LANG_LABEL_SUBMENU_AWMD_TITLE,
	LANG_LABEL_SUBMENU_AWMD_CONTENT0,
	LANG_LABEL_SUBMENU_AWMD_CONTENT1,
	LANG_LABEL_SUBMENU_POR_TITLE,
	LANG_LABEL_SUBMENU_POR_CONTENT0,
	LANG_LABEL_SUBMENU_POR_CONTENT1,
	LANG_LABEL_SUBMENU_GPS_TITLE,
	LANG_LABEL_SUBMENU_GPS_CONTENT0,
	LANG_LABEL_SUBMENU_GPS_CONTENT1,
	LANG_LABEL_SUBMENU_CELLULAR_TITLE,
	LANG_LABEL_SUBMENU_CELLULAR_CONTENT0,
	LANG_LABEL_SUBMENU_CELLULAR_CONTENT1,
	LANG_LABEL_SUBMENU_SILENTMODE_TITLE,
	LANG_LABEL_SUBMENU_SILENTMODE_CONTENT0,
	LANG_LABEL_SUBMENU_SILENTMODE_CONTENT1,
	LANG_LABEL_SUBMENU_WIFI_TITLE,
	LANG_LABEL_SUBMENU_WIFI_CONTENT0,
	LANG_LABEL_SUBMENU_WIFI_CONTENT1,
	LANG_LABEL_SUBMENU_TWM_TITLE,
	LANG_LABEL_SUBMENU_TWM_CONTENT0,
	LANG_LABEL_SUBMENU_TWM_CONTENT1,
#endif
	LANG_LABEL_SUBMENU_WB_TITLE,
	LANG_LABEL_SUBMENU_WB_CONTENT0,
	LANG_LABEL_SUBMENU_WB_CONTENT1,
	LANG_LABEL_SUBMENU_WB_CONTENT2,
	LANG_LABEL_SUBMENU_WB_CONTENT3,
	LANG_LABEL_SUBMENU_WB_CONTENT4,
	LANG_LABEL_SUBMENU_CONTRAST_TITLE,
	LANG_LABEL_SUBMENU_CONTRAST_CONTENT0,
	LANG_LABEL_SUBMENU_CONTRAST_CONTENT1,
	LANG_LABEL_SUBMENU_CONTRAST_CONTENT2,
	LANG_LABEL_SUBMENU_CONTRAST_CONTENT3,
	LANG_LABEL_SUBMENU_CONTRAST_CONTENT4,
	LANG_LABEL_SUBMENU_CONTRAST_CONTENT5,
	LANG_LABEL_SUBMENU_EXPOSURE_TITLE,
	LANG_LABEL_SUBMENU_EXPOSURE_CONTENT0,
	LANG_LABEL_SUBMENU_EXPOSURE_CONTENT1,
	LANG_LABEL_SUBMENU_EXPOSURE_CONTENT2,
	LANG_LABEL_SUBMENU_EXPOSURE_CONTENT3,
	LANG_LABEL_SUBMENU_EXPOSURE_CONTENT4,
	LANG_LABEL_SUBMENU_EXPOSURE_CONTENT5,
	LANG_LABEL_SUBMENU_EXPOSURE_CONTENT6,
	LANG_LABEL_SUBMENU_SS_TITLE,
	LANG_LABEL_SUBMENU_SS_CONTENT0,
	LANG_LABEL_SUBMENU_SS_CONTENT1,
	LANG_LABEL_SUBMENU_SS_CONTENT2,
	LANG_LABEL_SUBMENU_SS_CONTENT3,
	LANG_LABEL_SUBMENU_OK,
	LANG_LABEL_SUBMENU_CANCEL,
	LANG_LABEL_SUBMENU_FORMAT_TITLE,
	LANG_LABEL_SUBMENU_FORMAT_TEXT,
	LANG_LABEL_SUBMENU_FORMATTING_TEXT,
	LANG_LABEL_SUBMENU_FRESET_TITLE,
	LANG_LABEL_SUBMENU_FRESET_TEXT,
	LANG_LABEL_TAKE_PICTURE,
	LANG_LABEL_WARNING,
	LANG_LABEL_TIPS,
	LANG_LABEL_NO_TFCARD,
	LANG_LABEL_TFCARD_FULL,
	LANG_LABEL_FORMATTING,
	LANG_LABEL_AP_SWITCH,
	LANG_LABEL_AP_ON,
	LANG_LABEL_AP_OFF,
	LANG_LABEL_AP_SSID,
	LANG_LABEL_AP_PASSWORD,
	LANG_LABEL_DATE_TITLE,
	LANG_LABEL_DATE_YEAR,
	LANG_LABEL_DATE_MONTH,
	LANG_LABEL_DATE_DAY,
	LANG_LABEL_DATE_HOUR,
	LANG_LABEL_DATE_MINUTE,
	LANG_LABEL_DATE_SECOND,
	LANG_LABEL_DELETEFILE_TITLE,
	LANG_LABEL_DELETEFILE_TEXT,		/* line 81 */
	LANG_LABEL_SHUTDOWN_TITLE,
	LANG_LABEL_SHUTDOWN_TEXT,		/* line 83*/
	LANG_LABEL_OPEN_USB_STORAGE_DEVICE,
	LANG_LABEL_CLOSE_USB_STORAGE_DEVICE,
	LANG_LABEL_CHARGE_MODE,		/* line 86 */
	LANG_LABEL_LOW_POWER_SHUTDOWN,
	LANG_LABEL_10S_SHUTDOWN,
	LANG_LABEL_SHUTDOWN_NOW,
	LANG_LABEL_30S_NOWORK_SHUTDOWN,
	LANG_LABEL_PLAYBACK_FAIL,
	LANG_LABEL_FILELIST_EMPTY
};


namespace android {

class cdrLang
{
public:
	cdrLang();
	virtual ~cdrLang(){}
	virtual int initLangAndFont(void) = 0;

	int initLabel(void);
	const char* getLabel(unsigned int labelIndex);

	LANGUAGE lang;
	PLOGFONT mLogFont;

private:
	Vector <String8> label;
	int loadLabelFromLangFile(String8 langFile);
	int UTF8_to_MBS();
};

}




#endif
